//Actions for config organization
export const RESET_ORG_CONFIG = 'RESET_ORG_CONFIG';
export const SET_ORG_CONFIG = 'SET_ORG_CONFIG';
export const ADD_ADMIN_TO_ORG_CONFIG = 'ADD_ADMIN_TO_ORG_CONFIG';
export const REMOVE_ADMIN_FROM_ORG_CONFIG = 'REMOVE_ADMIN_FROM_ORG_CONFIG';
export const CHANGE_NP_ORG_CONFIG = 'CHANGE_NP_ORG_CONFIG';
export const CHANGE_IMPORT_URL_ORG_CONFIG = 'CHANGE_IMPORT_URL_ORG_CONFIG';
export const UPDATE_EVENT_IMPORT_CONFIG = 'UPDATE_EVENT_IMPORT_CONFIG';
export const UPDATE_SYNC_STATE_TO_NP = 'UPDATE_SYNC_STATE_TO_NP';
export const UPDATE_SYNC_CATEGORY_TO_NP = 'UPDATE_SYNC_CATEGORY_TO_NP';
export const UPDATE_CONFIG_COMMIT = 'UPDATE_CONFIG_COMMIT';
export const UPDATE_IMPORT_EVENT_URL_FAILED = 'UPDATE_IMPORT_EVENT_URL_FAILED';

//Actions for config networking platform
export const RESET_NP_CONFIG = 'RESET_NP_CONFIG';
export const SET_NP_CONFIG = 'SET_NP_CONFIG';
export const ADD_ADMIN_TO_NP_CONFIG = 'ADD_ADMIN_TO_NP_CONFIG';
export const REMOVE_ADMIN_FROM_NP_CONFIG = 'REMOVE_ADMIN_FROM_NP_CONFIG';
export const CHANGE_NP_DESCRIPTION = 'CHANGE_NP_DESCRIPTION';
export const CHANGE_NP_WEBSITE = 'CHANGE_NP_WEBSITE';
export const CHANGE_NP_MANUALLY_ACCEPT_ORG = 'CHANGE_NP_MANUALLY_ACCEPT_ORG';
export const UPDATE_NP_CONFIG_COMMIT = 'UPDATE_NP_CONFIG_COMMIT';